### ISSUE TITLE
Link to QA DAN code broken in README

### ISSUE THREAD

**Issue by aravindsiv** [miyyer/dan#3]
The link to the QA DAN code in README seems to be broken, and the linked [repo](https://github.com/pinafore/qb) has undergone a significant amount of changes.

**Comment by miyyer** [comment]
yes, the quiz bowl code has undergone a lot of changes, and the QA DAN has been reimplemented in keras instead of numpy. the "build_model" function of the linked file (https://github.com/Pinafore/qb/blob/master/qanta/guesser/dan.py) contains the network architecture setup which can be re-used for other classification tasks.
